version: '3.1'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - backend

  postgres:
    image: toleg/postgres_mysql_fdw
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
